### ISSUE TITLE
apollo-link-schema docs don't explain what it is

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-link#359]
I had to read the source of apollo-link-schema to understand what it did. The docs don't explain that it is a terminal link which executes the query against a compiled schema with resolvers.

I also find the name to be confusing. I would expect apollo-link-schema to be something like "provide a copy of the schema language schema so that the client can type-check it before sending requests on the network" or something. The name doesn't at all indicate that it actually executes the query itself. I'd expect this to be called something like apollo-link-direct-execution or apollo-link-local-execution. Or maybe just apollo-link-execute since that's the method that's called!

**Comment by glasser** [comment]
Cc @zephraph

**Comment by zephraph** [comment]
The docs do need to be enhanced. Currently it's missing the **purpose** and **options** sections that some of the other links have. 

As for the name, here's the original discussion: https://github.com/apollographql/apollo-link/pull/227#issuecomment-347844167. @jbaxleyiii can pitch in some more on that because it was his original suggestion. It was, and is, a little non-optimal from my perspective and it seems like different implementations on this tended to converge on **apollo-link-local**. At the time though, I was more focused on getting it done than having a long discussion on the name.

**Comment by glasser** [comment]
Yeah, I think the confusing thing for me personally naming-wise is that "schema" means two different things in the GraphQL context:

(a) A text document written in the GraphQL Schema language
(b) A GraphQLSchema object from the graphql-js library, perhaps manually constructed, perhaps built with graphql-tools from an "(a) schema"

This module uses schema to mean (b), but at least for me personally, the name more strongly implies (a).

**Comment by stubailo** [comment]
Definitely always time to rename it! But we should probably wait until James is back from vacation to do that if we decide it's a good idea. Also curious what @evans

**Comment by glasser** [comment]
Absolutely! Just giving some feedback :)
