### ISSUE TITLE
Discussion: Observable or AsyncIterator

### ISSUE THREAD

**Issue by hlehmann** [apollographql/apollo-link#53]
Because it seems to be central, I am wandering if it should directly use AsyncIterator instead of Observable.
AsyncIterator seems to be in a better place to become standard. It's also used for graphql subscriptions.

What are the avantages of Observable ?

**Comment by jbaxleyiii** [comment]
I think its an interesting idea to discus the pros and cos of both!

**Comment by jbaxleyiii** [comment]
cc @evans

**Comment by evans** [comment]
This [explanation](https://github.com/tc39/proposal-async-iteration/issues/25#issuecomment-246230211) of the two data structures is the best I found. While almost equivalent, the difference is that AsyncIterators are single pull(`next`) and single push(`Promise`) and Observables are single pull(`subscribe`) and multiple push(`next`, `error`, `complete`). 

I think the advantage of an Observable is the single `subscribe` call maps well to starting the data fetch/network request. This model works well for queries/mutations(single network request) and subscriptions(current websocket initialization occurs once). In addition, Observables inherently support multiple subscribers.

An AsyncIterator provides support for "backpressure", which may end up to be an advantage for fetches that require multiple network requests/a request for each result, since `next` would map one to one with fetch calls. This type of interaction would be ideal for polling. In order to support live data or some other form of server pushes, the AsyncIterators must keep a buffer of responses to service the `next`'s in order.

Observables work well for Links with the current mode of operating, since they put the onus of data retrieval on the data source rather than on the requester and source. My first attempt at using an AsyncIterator seems to require a lot more boilerplate to handle the multiple/live results(non-buffered). I haven't worked with an AsyncIterator deeply before, so there are probably better libraries out there. 

```js
request(operation, forward){
  const asyncIterator = forward(operation);
  return {
    next: () => {

      //start network request on next call
      const request = asyncIterator.next();

      return new Promise ((resolve, reject) => {
        // start network request when promise needs resolution
        // asyncIterator.next()
        request
          .then(({ value, done }) => {
            if (done) {
              console.log("completed");
            } else {
              console.log(`data: ${value}`);
            }
            resolve({ value, done });
          })
          .catch(error => {
            console.log("error");
            reject(error);
          });
      })
    }
  };
}
```

As an added bonus, Observables provide seamless integration with Angular services. 

Please let me know if there are other use cases that AsyncIterators fit better or Observables handle poorly. Happy to reconsider!
