### ISSUE TITLE
Use Async Generators instead of zen-observable

### ISSUE THREAD

**Issue by crubier** [apollographql/apollo-link#774]
Apollo link makes heavy use of `zen-observable`. 

However ES2018 features async generators, aka async iterators, and it seems to me that they are a replacement for Observables, with less object-orientation smell.

Since Async generators are now a standard feature of javascript (and python, and C#, and others...), I believe apollo should be using those.

I understand that it would probably need breaking changes (or maybe it wouldn't ?), but I believe it would make sense in the longer term.

**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by JoviDeCroock** [comment]
Closing this since it is not really a bug report, you can always go to any of these mediums, this belongs in the feature requests I think:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-link` tag): https://stackoverflow.com/questions/tagged/apollo-link
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

Just a personal touch in this is that async generators will bloat the bundle size a lot.

**Comment by crubier** [comment]
I understand the bundle size remark but respectfully disagree as:

  - zen observable and some other dependencies would not be needed anymore, making the bundle lighter
  - async generators will be supported natively on all platforms so there would not be additional code in the longer term
