### ISSUE TITLE
Is there a way to detect API calls (internet traffic) on my site with React Apollo?

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-link#792]
Is there a way to detect API calls (internet traffic) on my site with React Apollo?

I need to know in React Apollo (true / false) if something is requested through my browser page...

With jQuery I was using $(document).ajaxStart(() => {} - $(document).ajaxStop(() => {}

Is there something similar in React Apollo world?

**Comment by JoviDeCroock** [comment]
Well in theory you could add it to your link package, since before a fetch is started it passes there. 

If you could further elaborate on your use case I could be of more assistance

**Comment by JoviDeCroock** [comment]
Closing this since it is not really a bug report, you can always ask for help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
